export const GET_SELLER = 'GET_SELLER';

export const ADD_CART = 'ADD_CART';

export const DECREASE_CART = 'DECREASE_CART';

export const COMPUTE_CART = 'COMPUTE_CART';

export const EMPTY_CART = 'EMPTY_CART';

export const SET_TOOLINFO = 'SET_TOOLINFO';

export const EMPTY_TOOLINFO = 'EMPTY_TOOLINFO';

export const GET_DISCOUNTDESC = 'GET_DISCOUNTDESC';

export const COMPUTE_FULLREDUCE = 'COMPUTE_FULLREDUCE';

export const SET_LOCALSTORE = 'SET_LOCALSTORE';

export const GET_LOCALSTORE = 'GET_LOCALSTORE';

export const SET_SELLERID = 'SET_SELLERID';

export const SET_SELLERS = 'SET_SELLERS';

export const EMPTY_BYID = 'EMPTY_BYID';

export const SET_LOCALSTOREBYID = 'SET_LOCALSTOREBYID';
